/** Mirrors `ml/models/pretrained/yolov8_chess_pieces.json` — do not tune here. */
export const YOLO_CHESS_PIECES_CONFIG = {
  inputSize: 640,
  inputName: "images",
  outputName: "output0",
  confThreshold: 0.3,
  iouThreshold: 0.45,
  skipClasses: new Set(["board"]),
  localizationOnly: false,
  boardClassIndex: 0,
  coordsNormalized: true,
  maxBoxRatio: 0.32,
  minBoxPx: 18,
  classNames: [
    "board",
    "white_king",
    "white_queen",
    "white_rook",
    "white_bishop",
    "white_knight",
    "white_pawn",
    "black_king",
    "black_queen",
    "black_rook",
    "black_bishop",
    "black_knight",
    "black_pawn",
  ] as const,
} as const;

export const YOLO_LABEL_TO_FEN: Record<string, string> = {
  white_pawn: "P",
  white_knight: "N",
  white_bishop: "B",
  white_rook: "R",
  white_queen: "Q",
  white_king: "K",
  black_pawn: "p",
  black_knight: "n",
  black_bishop: "b",
  black_rook: "r",
  black_queen: "q",
  black_king: "k",
};
